name: getx_skeleton
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons:
  get: # for state management and context less stuff

  logger: # log events in clear way insted of (print)

  flutter_screenutil: ^5.2.0

  dio: #  for api requests
  http_mock_adapter: # mocking dio for testing
  pretty_dio_logger: # for dio api logging and debugging

  hive: # local database (SQFlite replacement)
  hive_flutter: # make it easy to use hive (no need fo r path provider)
  shared_preferences: # shared preferences persistence key value store
 
  firebase_core: # to initialize firebase services
  firebase_messaging: # fcm services
  awesome_notifications: ^0.7.4+1 # notifications services (will be used for fcm)

  flutter_launcher_icons: # change app icon
  change_app_package_name: # change package name
  rename_app: # rename app
  retrofit:
  animated_notch_bottom_bar: ^1.0.0

  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  confirm_dialog: ^1.0.2
  in_app_purchase_android: ^0.3.0+10
  in_app_purchase: ^3.1.7

dev_dependencies:
  mockito:
  flutter_lints:
  build_runner: # generate dart files
  hive_generator: # generate hive files
  retrofit_generator:
  freezed_annotation: ^2.4.1
  json_serializable:
  package_rename: ^1.3.3
  integration_test:
    sdk: flutter
  freezed: ^2.4.1

  flutter_test:
    sdk: flutter
dependency_overrides:
  collection:
  analyzer:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900
package_rename_config:
  android:
    app_name: Banko Team
    package_name: bt.com.banko_team 
